In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Load Data Set

In [2]:
df = pd.read_csv('Activity.csv')
df

/shared/centos7/anaconda3/2021.05/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,IPC Flag,Cust ID,ERP Combined Start Fiscal Year,ERP Combined Start Fiscal Week,Product Division,Article,Style Desc,ERP Gender,ERP Master Gender,ERP Season Cd Opened,UPC,US Size,ASIN,ERP Ooh Qty,ERP Ooh,ERP Cancel Qty,ERP Cancel,ERP Sls Qty,ERP Sls
0,IPC,4000828,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,MNS,20213,194580280119,XXL,B0916SMSN2,2.0,65.00,1.0,32.5,NaN,NaN
1,IPC,4000828,2022,15,Footwear,37101305,Cool Cat Wns,WNS,WNS,20191,192340698204,7,B07TLY4W7F,1.0,16.50,NaN,NaN,NaN,NaN
2,IPC,4000828,2022,15,Footwear,37032502,CARINA L,WNS,WNS,20191,192340682746,9.5,B07HJNY1N5,1.0,35.75,NaN,NaN,NaN,NaN
3,IPC,4000828,2022,15,Apparel,58644602,ESS LOGO TEE BT,MNS,MNS,20203,194577192463,XLT,B084FW9VFR,25.0,312.50,NaN,NaN,NaN,NaN
4,IPC,4000828,2022,15,Apparel,58644601,ESS LOGO TEE BT,MNS,MNS,20203,194577192562,2XL,B084FWVHRT,21.0,262.50,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065009,IPC,4000828,2021,8,Footwear,37234302,SEGA Leadcat FTR SONIC PS,PSC,KIDS,20201,193525480508,3,B07TJRHTLB,NaN,NaN,NaN,NaN,2.0,25.0
2065010,IPC,4000828,2021,5,Footwear,37386102,COOLCAT SPORT RETRO PS,PSC,KIDS,20201,193526285744,3,B08KRRRPKP,NaN,NaN,NaN,NaN,2.0,25.0
2065011,IPC,4000828,2021,11,Footwear,37102521,Cool Cat Jr,JNR,KIDS,20211,194579220645,4,B08KR7TBMD,NaN,NaN,NaN,NaN,2.0,25.0
2065012,IPC,4000828,2021,13,Footwear,37102602,COOL CAT PS,PSC,KIDS,20191,193526193018,2,B08KR3777P,NaN,NaN,NaN,NaN,2.0,27.5
2065013,IPC,4000828,2021,7,Footwear,37102502,Cool Cat Jr,JNR,KIDS,20191,193526189899,5,B07TMXRWKL,NaN,NaN,NaN,NaN,2.0,27.5

### Find Number of Values in each category

In [3]:
df['Product Division'].value_counts()

Footwear       1452906
Apparel         606576
Accessories       5532
Name: Product Division, dtype: int64

### Remove NA under Cancelled Qty

In [4]:
#df = df[df['ERP Cancel Qty'].notna()]

In [5]:
df.shape

(2065014, 19)

### How many N/A

In [6]:
df.isnull().sum()

IPC Flag                                0
Cust ID                                 0
ERP Combined Start Fiscal Year          0
ERP Combined Start Fiscal Week          0
Product Division                        0
Article                                 0
Style Desc                              0
ERP Gender                              0
ERP Master Gender                       0
ERP Season Cd Opened                    0
UPC                                     0
US Size                               270
ASIN                               248114
ERP Ooh Qty                       2061462
ERP Ooh                           2061462
ERP Cancel Qty                     360944
ERP Cancel                         360944
ERP Sls Qty                       1656849
ERP Sls                           1656849
dtype: int64

In [7]:
df = df.dropna(subset=['US Size'])

In [8]:
df.isnull().sum()

IPC Flag                                0
Cust ID                                 0
ERP Combined Start Fiscal Year          0
ERP Combined Start Fiscal Week          0
Product Division                        0
Article                                 0
Style Desc                              0
ERP Gender                              0
ERP Master Gender                       0
ERP Season Cd Opened                    0
UPC                                     0
US Size                                 0
ASIN                               247844
ERP Ooh Qty                       2061192
ERP Ooh                           2061192
ERP Cancel Qty                     360944
ERP Cancel                         360944
ERP Sls Qty                       1656579
ERP Sls                           1656579
dtype: int64

In [9]:
df.head()

,IPC Flag,Cust ID,ERP Combined Start Fiscal Year,ERP Combined Start Fiscal Week,Product Division,Article,Style Desc,ERP Gender,ERP Master Gender,ERP Season Cd Opened,UPC,US Size,ASIN,ERP Ooh Qty,ERP Ooh,ERP Cancel Qty,ERP Cancel,ERP Sls Qty,ERP Sls
0,IPC,4000828,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,MNS,20213,194580280119,XXL,B0916SMSN2,2.0,65.00,1.0,32.5,NaN,NaN
1,IPC,4000828,2022,15,Footwear,37101305,Cool Cat Wns,WNS,WNS,20191,192340698204,7,B07TLY4W7F,1.0,16.50,NaN,NaN,NaN,NaN
2,IPC,4000828,2022,15,Footwear,37032502,CARINA L,WNS,WNS,20191,192340682746,9.5,B07HJNY1N5,1.0,35.75,NaN,NaN,NaN,NaN
3,IPC,4000828,2022,15,Apparel,58644602,ESS LOGO TEE BT,MNS,MNS,20203,194577192463,XLT,B084FW9VFR,25.0,312.50,NaN,NaN,NaN,NaN
4,IPC,4000828,2022,15,Apparel,58644601,ESS LOGO TEE BT,MNS,MNS,20203,194577192562,2XL,B084FWVHRT,21.0,262.50,NaN,NaN,NaN,NaN

### Drop unnecessary columns

In [10]:
df = df.drop(columns=['IPC Flag', 'Cust ID', 'ASIN'])

### Remove spaces from columns

In [11]:
df.rename(columns = {'ERP Combined Start Fiscal Year': 'ERP_Combined_Start_Fiscal_Year', 'ERP Combined Start Fiscal Week': 'ERP_Combined_Start_Fiscal_Week', 'Product Division': 'Product_Division', 'Style Desc': 'Style_Desc', 'ERP Gender': 'ERP_Gender','ERP Master Gender': 'ERP_Master_Gender', 'ERP Season Cd Opened':'ERP_Season_Cd_Opened', 'US Size': 'US_Size', 'ERP Ooh Qty': 'ERP_Ooh_Qty', 'ERP Ooh': 'ERP_Ooh', 'ERP Cancel Qty': 'ERP_Cancel_Qty', 'ERP Cancel': 'ERP_Cancel', 'ERP Sls Qty': 'ERP_Sls_Qty', 'ERP Sls': 'ERP_Sls'}, inplace = True)

### Fill N/A with 0

In [12]:
df['ERP_Ooh_Qty'] = df['ERP_Ooh_Qty'].fillna(0)
df['ERP_Ooh'] = df['ERP_Ooh'].fillna(0)
df['ERP_Sls_Qty'] = df['ERP_Sls_Qty'].fillna(0)
df['ERP_Sls'] = df['ERP_Sls'].fillna(0)
df['ERP_Cancel_Qty'] = df['ERP_Cancel_Qty'].fillna(0)
df['ERP_Cancel'] = df['ERP_Cancel'].fillna(0)

In [13]:
df.isna().sum()

ERP_Combined_Start_Fiscal_Year    0
ERP_Combined_Start_Fiscal_Week    0
Product_Division                  0
Article                           0
Style_Desc                        0
ERP_Gender                        0
ERP_Master_Gender                 0
ERP_Season_Cd_Opened              0
UPC                               0
US_Size                           0
ERP_Ooh_Qty                       0
ERP_Ooh                           0
ERP_Cancel_Qty                    0
ERP_Cancel                        0
ERP_Sls_Qty                       0
ERP_Sls                           0
dtype: int64

In [14]:
df.head()

,ERP_Combined_Start_Fiscal_Year,ERP_Combined_Start_Fiscal_Week,Product_Division,Article,Style_Desc,ERP_Gender,ERP_Master_Gender,ERP_Season_Cd_Opened,UPC,US_Size,ERP_Ooh_Qty,ERP_Ooh,ERP_Cancel_Qty,ERP_Cancel,ERP_Sls_Qty,ERP_Sls
0,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,MNS,20213,194580280119,XXL,2.0,65.00,1.0,32.5,0.0,0.0
1,2022,15,Footwear,37101305,Cool Cat Wns,WNS,WNS,20191,192340698204,7,1.0,16.50,0.0,0.0,0.0,0.0
2,2022,15,Footwear,37032502,CARINA L,WNS,WNS,20191,192340682746,9.5,1.0,35.75,0.0,0.0,0.0,0.0
3,2022,15,Apparel,58644602,ESS LOGO TEE BT,MNS,MNS,20203,194577192463,XLT,25.0,312.50,0.0,0.0,0.0,0.0
4,2022,15,Apparel,58644601,ESS LOGO TEE BT,MNS,MNS,20203,194577192562,2XL,21.0,262.50,0.0,0.0,0.0,0.0

### Bring in Product data set

In [15]:
df1 = pd.read_csv('Product.csv')
df1

/shared/centos7/anaconda3/2021.05/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (0,9,14) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Article[Article],Article[Color Desc],Article[ERP Gender],Article[ERP Master Gender],Article[ERP Season Cd Opened],Article[Main Color Group Desc],Article[Product Division],Article[Reporting Business Unit],Article[Style Desc],Article[Style Family],Article[Style Num],SKU[Height (in)],SKU[Length (in)],SKU[UPC],SKU[US Size],SKU[Weight (g)],SKU[Width (in)]
0,36735101,Peacoat-Puma White-Ribbon Red-Strong Blue,INF,KIDS,20183,blue,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320764,10.5,0.0,0.0
1,36735101,Peacoat-Puma White-Ribbon Red-Strong Blue,INF,KIDS,20183,blue,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320429,12.5,0.0,0.0
2,36735101,Peacoat-Puma White-Ribbon Red-Strong Blue,INF,KIDS,20183,blue,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320863,11.5,0.0,0.0
3,36735102,Ribbon Red-Peacoat-Puma White-Puma Team Gold,INF,KIDS,20183,red,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320924,13.5,0.0,0.0
4,36735102,Ribbon Red-Peacoat-Puma White-Puma Team Gold,INF,KIDS,20183,red,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320795,12.5,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660946,53994501,puma black,WNS,WNS,20223,black,Apparel,Basketball,FOUNDATION SHORT,NaN,539945.0,0.4,15.7,195552276031,L,270.0,11.0
660947,53994501,puma black,WNS,WNS,20223,black,Apparel,Basketball,FOUNDATION SHORT,NaN,539945.0,0.4,15.7,195552276048,XL,270.0,11.0
660948,76767106,puma black,MNS,MNS,20223,black,Apparel,Teamsport,BVB Training Shorts,NaN,767671.0,0.4,15.7,195101554641,XS,170.0,11.0
660949,53668701,puma black,MNS,MNS,20223,black,Apparel,Motorsport,BMW MMS METAL ENERGY LOGO TEE,NaN,536687.0,0.4,15.7,195101895867,XS,177.0,11.0
660950,53006301,puma black,MNS,MNS,20223,black,Apparel,Golf,Jackpot Jogger,NaN,530063.0,0.4,15.7,194578179142,28/32,478.0,11.0

In [16]:
df1.rename(columns = {'SKU[UPC]': 'UPC'}, inplace = True)

In [17]:
df1.shape

(660951, 17)

In [18]:
df1.head()

,Article[Article],Article[Color Desc],Article[ERP Gender],Article[ERP Master Gender],Article[ERP Season Cd Opened],Article[Main Color Group Desc],Article[Product Division],Article[Reporting Business Unit],Article[Style Desc],Article[Style Family],Article[Style Num],SKU[Height (in)],SKU[Length (in)],UPC,SKU[US Size],SKU[Weight (g)],SKU[Width (in)]
0,36735101,Peacoat-Puma White-Ribbon Red-Strong Blue,INF,KIDS,20183,blue,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320764,10.5,0.0,0.0
1,36735101,Peacoat-Puma White-Ribbon Red-Strong Blue,INF,KIDS,20183,blue,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320429,12.5,0.0,0.0
2,36735101,Peacoat-Puma White-Ribbon Red-Strong Blue,INF,KIDS,20183,blue,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320863,11.5,0.0,0.0
3,36735102,Ribbon Red-Peacoat-Puma White-Puma Team Gold,INF,KIDS,20183,red,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320924,13.5,0.0,0.0
4,36735102,Ribbon Red-Peacoat-Puma White-Puma Team Gold,INF,KIDS,20183,red,Footwear,Sportstyle Kids,SUEDE CLASSIC MULTICOLOR EMB PS,Suede,367351.0,0.0,0.0,191241320795,12.5,0.0,0.0

In [19]:
df.shape

(2064744, 16)

### Merge the color column to the main data set

In [20]:
new = pd.merge(df, df1, how='inner')
pd.set_option("display.max_columns", None)
new

,ERP_Combined_Start_Fiscal_Year,ERP_Combined_Start_Fiscal_Week,Product_Division,Article,Style_Desc,ERP_Gender,ERP_Master_Gender,ERP_Season_Cd_Opened,UPC,US_Size,ERP_Ooh_Qty,ERP_Ooh,ERP_Cancel_Qty,ERP_Cancel,ERP_Sls_Qty,ERP_Sls,Article[Article],Article[Color Desc],Article[ERP Gender],Article[ERP Master Gender],Article[ERP Season Cd Opened],Article[Main Color Group Desc],Article[Product Division],Article[Reporting Business Unit],Article[Style Desc],Article[Style Family],Article[Style Num],SKU[Height (in)],SKU[Length (in)],SKU[US Size],SKU[Weight (g)],SKU[Width (in)]
0,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,MNS,20213,194580280119,XXL,2.0,65.0,1.0,32.5,0.0,0.0,53119001,puma black,MNS,MNS,20213,black,Apparel,Motorsport,BMW MMS SWEATSHORTS,NaN,531190.0,0.4,7.1,XXL,335.0,8.7
1,2021,44,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,5.0,162.5,53119001,puma black,MNS,MNS,20213,black,Apparel,Motorsport,BMW MMS SWEATSHORTS,NaN,531190.0,0.4,7.1,XXL,335.0,8.7
2,2021,47,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,9.0,292.5,53119001,puma black,MNS,MNS,20213,black,Apparel,Motorsport,BMW MMS SWEATSHORTS,NaN,531190.0,0.4,7.1,XXL,335.0,8.7
3,2021,43,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,4.0,130.0,53119001,puma black,MNS,MNS,20213,black,Apparel,Motorsport,BMW MMS SWEATSHORTS,NaN,531190.0,0.4,7.1,XXL,335.0,8.7
4,2021,35,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,7.0,227.5,53119001,puma black,MNS,MNS,20213,black,Apparel,Motorsport,BMW MMS SWEATSHORTS,NaN,531190.0,0.4,7.1,XXL,335.0,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2064366,2021,21,Apparel,53306327,CLASSICS CUT-OUT TOP,WNS,WNS,20211,194580457566,L,0.0,0.0,0.0,0.0,2.0,30.0,53306327,Cloud Pink,WNS,WNS,20211,red,Apparel,Sportstyle Prime / Select,CLASSICS CUT-OUT TOP,NaN,533063.0,0.4,11.0,L,95.0,7.9
2064367,2021,16,Apparel,53073003,BP SS TEE 1,MNS,MNS,20211,194579080102,XS,0.0,0.0,0.0,0.0,2.0,30.0,53073003,SOFT FLUO YELLOW,MNS,MNS,20211,yellow,Apparel,Basketball,BP SS TEE 1,NaN,530730.0,0.4,15.7,XS,225.0,11.0
2064368,2021,9,Apparel,58661826,EVOSTRIPE TANK,WNS,WNS,20211,194578416933,XS,0.0,0.0,0.0,0.0,2.0,25.0,58661826,Apricot Blush,WNS,WNS,20211,pink,Apparel,Sportstyle Core,EVOSTRIPE TANK,NaN,586618.0,0.4,15.7,XS,115.0,11.0
2064369,2021,17,Apparel,53023523,ICONIC T7 BRALETTE,WNS,WNS,20211,194578081452,S,0.0,0.0,0.0,0.0,2.0,25.0,53023523,poppy red,WNS,WNS,20211,red,Apparel,Sportstyle Prime / Select,ICONIC T7 BRALETTE,NaN,530235.0,0.4,15.7,S,100.0,11.0
2064370,2021,28,Apparel,58788827,REBEL CROP TANK,WNS,WNS,20211,194578327536,XS,0.0,0.0,0.0,0.0,2.0,25.0,58788827,Cloud Pink,WNS,WNS,20211,pink,Apparel,Sportstyle Core,REBEL CROP TANK,NaN,587888.0,0.4,10.2,XS,103.0,7.5

### Drop Unneccessary Columns

In [21]:
new.columns

Index(['ERP_Combined_Start_Fiscal_Year', 'ERP_Combined_Start_Fiscal_Week',
       'Product_Division', 'Article', 'Style_Desc', 'ERP_Gender',
       'ERP_Master_Gender', 'ERP_Season_Cd_Opened', 'UPC', 'US_Size',
       'ERP_Ooh_Qty', 'ERP_Ooh', 'ERP_Cancel_Qty', 'ERP_Cancel', 'ERP_Sls_Qty',
       'ERP_Sls', 'Article[Article]', 'Article[Color Desc]',
       'Article[ERP Gender]', 'Article[ERP Master Gender]',
       'Article[ERP Season Cd Opened]', 'Article[Main Color Group Desc]',
       'Article[Product Division]', 'Article[Reporting Business Unit]',
       'Article[Style Desc]', 'Article[Style Family]', 'Article[Style Num]',
       'SKU[Height (in)]', 'SKU[Length (in)]', 'SKU[US Size]',
       'SKU[Weight (g)]', 'SKU[Width (in)]'],
      dtype='object')

In [22]:
new.drop(['Article[Article]', 'Article[Color Desc]',
       'Article[ERP Gender]', 'Article[ERP Master Gender]',
       'Article[ERP Season Cd Opened]',
       'Article[Product Division]', 'Article[Reporting Business Unit]',
       'Article[Style Desc]', 'Article[Style Family]', 'Article[Style Num]',
       'SKU[Height (in)]', 'SKU[Length (in)]', 'SKU[US Size]',
       'SKU[Weight (g)]', 'SKU[Width (in)]', 'ERP_Master_Gender'], axis=1, inplace=True)

In [23]:
new.head()

,ERP_Combined_Start_Fiscal_Year,ERP_Combined_Start_Fiscal_Week,Product_Division,Article,Style_Desc,ERP_Gender,ERP_Season_Cd_Opened,UPC,US_Size,ERP_Ooh_Qty,ERP_Ooh,ERP_Cancel_Qty,ERP_Cancel,ERP_Sls_Qty,ERP_Sls,Article[Main Color Group Desc]
0,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,2.0,65.0,1.0,32.5,0.0,0.0,black
1,2021,44,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,5.0,162.5,black
2,2021,47,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,9.0,292.5,black
3,2021,43,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,4.0,130.0,black
4,2021,35,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,7.0,227.5,black

### Rename column color

In [24]:
new.rename(columns = {'Article[Main Color Group Desc]': 'Color', 'ERP_Gender':'Gender', 'ERP_Season_Cd_Opened':'Season_Opened', 'ERP_Combined_Start_Fiscal_Year':'Fiscal_Year', 'ERP_Combined_Start_Fiscal_Week':'Fiscal_Week', 'ERP_Ooh_Qty': 'On_Hand_Qty', 'ERP_Ooh':'On_Hand_Value', 'ERP_Cancel_Qty':'Cancelled_Qty', 'ERP_Cancel':'Cancelled_Value', 'ERP_Sls_Qty':'Shipped_Qty', 'ERP_Sls':'Shipped_Value'}, inplace = True)

In [25]:
new.shape

(2064371, 16)

In [26]:
df.isna().sum()

ERP_Combined_Start_Fiscal_Year    0
ERP_Combined_Start_Fiscal_Week    0
Product_Division                  0
Article                           0
Style_Desc                        0
ERP_Gender                        0
ERP_Master_Gender                 0
ERP_Season_Cd_Opened              0
UPC                               0
US_Size                           0
ERP_Ooh_Qty                       0
ERP_Ooh                           0
ERP_Cancel_Qty                    0
ERP_Cancel                        0
ERP_Sls_Qty                       0
ERP_Sls                           0
dtype: int64

In [27]:
new.head()

,Fiscal_Year,Fiscal_Week,Product_Division,Article,Style_Desc,Gender,Season_Opened,UPC,US_Size,On_Hand_Qty,On_Hand_Value,Cancelled_Qty,Cancelled_Value,Shipped_Qty,Shipped_Value,Color
0,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,2.0,65.0,1.0,32.5,0.0,0.0,black
1,2021,44,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,5.0,162.5,black
2,2021,47,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,9.0,292.5,black
3,2021,43,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,4.0,130.0,black
4,2021,35,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,7.0,227.5,black

### Add Total Demand Column

In [28]:
new['Total_Demand_Qty'] = new['Cancelled_Qty'] + new['Shipped_Qty'] + new['On_Hand_Qty']
new['Total_Demand_Value'] = new['On_Hand_Value'] + new['Cancelled_Value'] + new['Shipped_Value']
new.head()

,Fiscal_Year,Fiscal_Week,Product_Division,Article,Style_Desc,Gender,Season_Opened,UPC,US_Size,On_Hand_Qty,On_Hand_Value,Cancelled_Qty,Cancelled_Value,Shipped_Qty,Shipped_Value,Color,Total_Demand_Qty,Total_Demand_Value
0,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,2.0,65.0,1.0,32.5,0.0,0.0,black,3.0,97.5
1,2021,44,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,5.0,162.5,black,5.0,162.5
2,2021,47,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,9.0,292.5,black,9.0,292.5
3,2021,43,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,4.0,130.0,black,4.0,130.0
4,2021,35,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,7.0,227.5,black,7.0,227.5

### Make Price Column

In [29]:
new['Price'] = new['Total_Demand_Value']/new['Total_Demand_Qty']
new.head()

,Fiscal_Year,Fiscal_Week,Product_Division,Article,Style_Desc,Gender,Season_Opened,UPC,US_Size,On_Hand_Qty,On_Hand_Value,Cancelled_Qty,Cancelled_Value,Shipped_Qty,Shipped_Value,Color,Total_Demand_Qty,Total_Demand_Value,Price
0,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,2.0,65.0,1.0,32.5,0.0,0.0,black,3.0,97.5,32.5
1,2021,44,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,5.0,162.5,black,5.0,162.5,32.5
2,2021,47,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,9.0,292.5,black,9.0,292.5,32.5
3,2021,43,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,4.0,130.0,black,4.0,130.0,32.5
4,2021,35,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,7.0,227.5,black,7.0,227.5,32.5

### Make a new data set for Apparels

In [30]:
apparel = new[(new.Product_Division == "Apparel")]

In [31]:
apparel.head()

,Fiscal_Year,Fiscal_Week,Product_Division,Article,Style_Desc,Gender,Season_Opened,UPC,US_Size,On_Hand_Qty,On_Hand_Value,Cancelled_Qty,Cancelled_Value,Shipped_Qty,Shipped_Value,Color,Total_Demand_Qty,Total_Demand_Value,Price
0,2022,15,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,2.0,65.0,1.0,32.5,0.0,0.0,black,3.0,97.5,32.5
1,2021,44,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,5.0,162.5,black,5.0,162.5,32.5
2,2021,47,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,9.0,292.5,black,9.0,292.5,32.5
3,2021,43,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,4.0,130.0,black,4.0,130.0,32.5
4,2021,35,Apparel,53119001,BMW MMS SWEATSHORTS,MNS,20213,194580280119,XXL,0.0,0.0,0.0,0.0,7.0,227.5,black,7.0,227.5,32.5

In [32]:
apparel.shape

(606330, 19)

### Export Apparel data set to csv file

In [33]:
apparel.to_csv('apparel.csv')

### Make Accessories Data set

In [34]:
accessories = new[(new.Product_Division == "Accessories")]

In [35]:
accessories.shape

(5508, 19)

### Export Accessories Data Set to CSV file

In [36]:
accessories.to_csv('accessories.csv')

### Make Footwear Data set

In [37]:
footwear = new[(new.Product_Division == "Footwear")]

In [38]:
footwear.shape

(1452533, 19)

In [39]:
footwear.to_csv('footwear.csv')